services:
  - type: web
    name: ul-senior-ups-modbus-tcp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn web_portal:app --host 0.0.0.0 --port $PORT
    plan: free
    autoDeploy: true
